services:
  application:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DB_HOST: "database"
      LOGS_DIR: "../logs"
    develop:
      watch:
        - action: rebuild
          path: .
          target: ./app
    volumes:
      - content:/coma/content
      - logs:/logs

  database:
    image: "postgres"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - coma_database:/var/lib/postgresql/data

  redis-images:
    image: "redis"
    restart: "always"
    expose:
      - 6379
    command: ["redis-server", "--appendonly", "no", "--save", "", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru"]
  
  redis:
    image: "redis"
    restart: "always"
    expose:
      - 6379
    command: ["redis-server", "--appendonly", "no", "--save", "", "--maxmemory", "25mb", "--maxmemory-policy", "allkeys-lru"]

volumes:
  content:
  coma_database:
  logs:
